/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:6f202aae-b58d-478a-87ab-dcf3002ff0ab",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_IXR96FgqP",
    "aws_user_pools_web_client_id": "n855o7e5c8qs3s2vvorgpan27",
    "oauth": {
        "domain": "naijagoingabroad-dev.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://naijagoingabroad.com/sign-in/",
        "redirectSignOut": "https://naijagoingabroad.com/sign-out/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "ngabroadbucket210504-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
