export const countries = [
  { name: "Australia" },
  { name: "Belgium" },
  { name: "Canada" },
  { name: "Cyprus" },
  { name: "Czech Republic" },
  { name: "Denmark" },
  { name: "Estonia" },
  { name: "Finland" },
  { name: "France" },
  { name: "Germany" },
  { name: "Greece" },
  { name: "Hungary" },
  { name: "Ireland" },
  { name: "Italy" },
  { name: "Lithuania" },
  { name: "Netherlands" },
  { name: "New Zealand" },
  { name: "Poland" },
  { name: "South Africa" },
  { name: "Spain" },
  { name: "Sweden" },
  { name: "Switzerland" },
  { name: "Turkey" },
  { name: "UAE" },
  { name: "UK" },
  { name: "USA" },
];
