export const countriesWithEmbassyInNigeria = [
  {
    id: 112,
    name: "Algeria",
    alias: "algeria",
  },
  {
    id: 114,
    name: "Angola",
    alias: "angola",
  },
  {
    id: 3,
    name: "Argentina",
    alias: "argentina",
  },
  {
    id: 4,
    name: "Australia",
    alias: "australia",
  },
  {
    id: 5,
    name: "Austria",
    alias: "austria",
  },
  {
    id: 118,
    name: "Barbados",
    alias: "barbados",
  },
  {
    id: 119,
    name: "Belarus",
    alias: "belarus",
  },
  {
    id: 7,
    name: "Belgium",
    alias: "belgium",
  },
  {
    id: 8,
    name: "Belize",
    alias: "belize",
  },
  {
    id: 124,
    name: "Botswana",
    alias: "botswana",
  },
  {
    id: 11,
    name: "Brazil",
    alias: "brazil",
  },
  {
    id: 12,
    name: "Bulgaria",
    alias: "bulgaria",
  },
  {
    id: 126,
    name: "Burkina Faso",
    alias: "burkina-faso",
  },
  {
    id: 129,
    name: "Cameroon",
    alias: "cameroon",
  },
  {
    id: 13,
    name: "Canada",
    alias: "canada",
  },
  {
    id: 131,
    name: "Chad",
    alias: "chad",
  },
  {
    id: 16,
    name: "China",
    alias: "china",
  },
  {
    id: 18,
    name: "Cuba",
    alias: "cuba",
  },
  {
    id: 19,
    name: "Cyprus",
    alias: "cyprus",
  },
  {
    id: 20,
    name: "Czech Republic",
    alias: "czech-republic",
  },
  {
    id: 21,
    name: "Denmark",
    alias: "denmark",
  },
  {
    id: 24,
    name: "Egypt",
    alias: "egypt",
  },
  {
    id: 137,
    name: "Equatorial Guinea",
    alias: "equatorial-guinea",
  },
  {
    id: 138,
    name: "Eritrea",
    alias: "eritrea",
  },
  {
    id: 139,
    name: "Ethiopia",
    alias: "ethiopia",
  },
  {
    id: 29,
    name: "Finland",
    alias: "finland",
  },
  {
    id: 31,
    name: "France",
    alias: "france",
  },
  {
    id: 141,
    name: "Gabon",
    alias: "gabon",
  },
  {
    id: 32,
    name: "Germany",
    alias: "germany",
  },
  {
    id: 33,
    name: "Ghana",
    alias: "ghana",
  },
  {
    id: 34,
    name: "Greece",
    alias: "greece",
  },
  {
    id: 216,
    name: "Greenland",
    alias: "greenland",
  },
  {
    id: 109,
    name: "Honduras",
    alias: "honduras",
  },
  {
    id: 37,
    name: "Hungary",
    alias: "hungary",
  },
  {
    id: 39,
    name: "India",
    alias: "india",
  },
  {
    id: 40,
    name: "Indonesia",
    alias: "indonesia",
  },
  {
    id: 41,
    name: "Ireland",
    alias: "ireland",
  },
  {
    id: 42,
    name: "Israel",
    alias: "israel",
  },
  {
    id: 43,
    name: "Italy",
    alias: "italy",
  },
  {
    id: 45,
    name: "Jamaica",
    alias: "jamaica",
  },
  {
    id: 46,
    name: "Japan",
    alias: "japan",
  },
  {
    id: 48,
    name: "Kenya",
    alias: "kenya",
  },
  {
    id: 54,
    name: "Malaysia",
    alias: "malaysia",
  },
  {
    id: 164,
    name: "Mali",
    alias: "mali",
  },
  {
    id: 55,
    name: "Malta",
    alias: "malta",
  },
  {
    id: 58,
    name: "Morocco",
    alias: "morocco",
  },
  {
    id: 59,
    name: "Namibia",
    alias: "namibia",
  },
  {
    id: 61,
    name: "Netherlands",
    alias: "netherlands",
  },
  {
    id: 66,
    name: "Norway",
    alias: "norway",
  },
  {
    id: 178,
    name: "Pakistan",
    alias: "pakistan",
  },
  {
    id: 217,
    name: "Palestine",
    alias: "palestine",
  },
  {
    id: 69,
    name: "Philippines",
    alias: "philippines",
  },
  {
    id: 70,
    name: "Poland",
    alias: "poland",
  },
  {
    id: 74,
    name: "Romania",
    alias: "romania",
  },
  {
    id: 75,
    name: "Russia",
    alias: "russia",
  },
  {
    id: 188,
    name: "Saudi Arabia",
    alias: "saudi-arabia",
  },
  {
    id: 78,
    name: "Senegal",
    alias: "senegal",
  },
  {
    id: 1510,
    name: "Serbia",
    alias: "serbia",
  },
  {
    id: 190,
    name: "Sierra Leone",
    alias: "sierra-leone",
  },
  {
    id: 79,
    name: "Singapore",
    alias: "singapore",
  },
  {
    id: 191,
    name: "Slovakia",
    alias: "slovakia",
  },
  {
    id: 80,
    name: "South Africa",
    alias: "south-africa",
  },
  {
    id: 82,
    name: "Spain",
    alias: "spain",
  },
  {
    id: 83,
    name: "Sweden",
    alias: "sweden",
  },
  {
    id: 84,
    name: "Switzerland",
    alias: "switzerland",
  },
  {
    id: 85,
    name: "Syria",
    alias: "syria",
  },
  {
    id: 86,
    name: "Taiwan",
    alias: "taiwan",
  },
  {
    id: 108,
    name: "Tanzania",
    alias: "tanzania",
  },
  {
    id: 87,
    name: "Thailand",
    alias: "thailand",
  },
  {
    id: 200,
    name: "Togo",
    alias: "togo",
  },
  {
    id: 203,
    name: "Tunisia",
    alias: "tunisia",
  },
  {
    id: 89,
    name: "Turkey",
    alias: "turkey",
  },
  {
    id: 206,
    name: "Uganda",
    alias: "uganda",
  },
  {
    id: 90,
    name: "Ukraine",
    alias: "ukraine",
  },
  {
    id: 245,
    name: "United Kingdom",
    alias: "united-kingdom",
  },
  {
    id: 91,
    name: "United States",
    alias: "united-states",
  },
  {
    id: 92,
    name: "Uruguay",
    alias: "uruguay",
  },
  {
    id: 93,
    name: "Venezuela",
    alias: "venezuela",
  },
  {
    id: 210,
    name: "Western Sahara",
    alias: "western-sahara",
  },
  {
    id: 214,
    name: "Zambia",
    alias: "zambia",
  },
  {
    id: 97,
    name: "Zimbabwe",
    alias: "zimbabwe",
  },
];

export const embassyAddress = [
  {
    Title: "Embassy of Belgium in Abuja, Nigeria",
    Field: "234 806 979 22 33 (visa), +234 803 301 68 22 (secretatiat)",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://diplomatie.belgium.be/nigeria",
    Field6: " http://diplomatie.belgium.be/nigeria ",
    Field7: "Email",
    Field8: "Abuja@diplobel.fed.be",
    Field9: "Abuja@diplobel.fed.be",
    Field10: "9, Usuma Street, Maitama  Abuja  Nigeria",
    Field11: "Address",
    Field12:
      "Monday to Thursday\r\n08:30 - 16:30\r\n\r\nFriday\r\n08:30 - 13:00",
    Field13: "OFFICE HOURS",
    Field14: "Dirk Verheyen - Ambassador \r\n",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/710",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of France in Abuja, Nigeria",
    Field: "[234] 7081156555",
    Field1: "Phone",
    Field2: "[234] (9) 523 54 82 / 523 52 84 (section consulair",
    Field3: "Fax",
    Field4: "Website",
    Field5: "https://ng.ambafrance.org/",
    Field6: " https://ng.ambafrance.org ",
    Field7: "Email",
    Field8: "sec-amb.abuja-amba@diplomatie.gouv.fr",
    Field9: "sec-amb.abuja-amba@diplomatie.gouv.fr",
    Field10: "37 Udi Hills Street Off Aso Drive Maitama - Abuja Nigeria",
    Field11: "Address",
    Field12: "\n8 AM - 4 PM",
    Field13: "OFFICE HOURS",
    Field14: "\nAmbassador: Jérôme Pasquier",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/711",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Japan in Nigeria",
    Field: "+234-9-413-8898 / 9258 / 9718 - 19",
    Field1: "Phone",
    Field2: "(870) 600-315-545",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "",
    Field9: "",
    Field10:
      "No. 9 Bobo Street (off Gana Street), Maitama, Abuja, Nigeria (P.M.B. 5070 WUSE)",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/712",
    caps: "SEND EDITS",
  },
  {
    Title: "United States Embassy in Abuja, Nigeria",
    Field: "(234)-9-461-4000",
    Field1: "Phone",
    Field2: "(234)-9-461-4036",
    Field3: "Fax",
    Field4: "Website",
    Field5: "https://ng.usembassy.gov/embassy-consulate/abuja/",
    Field6: " https://ng.usembassy.gov/embassy-consulate/abuja/ ",
    Field7: "Email",
    Field8: "AbujaACS@state.gov",
    Field9: "AbujaACS@state.gov",
    Field10: "Plot 1075 Diplomatic Drive Central District Area Abuja, Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\nAmbassador: W. Stuart Symington",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/713",
    caps: "SEND EDITS",
  },
  {
    Title: "High Commission of Tanzania in Abuja, Nigeria",
    Field: "(+234) 9 413 2313 (+234) 9 413 2312",
    Field1: "Phone",
    Field2: "(+234) 9 4132314",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "tanabuja@lycos.com",
    Field9: "tanabuja@lycos.com",
    Field10: "\n11, Ganges Street, Ministers Hill, Maitama",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/1583",
    caps: "SEND EDITS",
  },
  {
    Title: "High Commission of Pakistan in Abuja, Nigeria",
    Field: "(+234) (9) 3141650",
    Field1: "Phone",
    Field2: "(+234) (9) 3141652",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "pahicabuja@yahoo.com",
    Field9: "pahicabuja@yahoo.com",
    Field10: "1805 Samora Michel Street Off Yakubu Gowon Crescent Asokoro",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/2430",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of the Philippines in Abuja, Nigeria",
    Field: "(+234) 8051752187",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "abuja_pe@yahoo.co.uk",
    Field9: "abuja_pe@yahoo.co.uk",
    Field10:
      "Plot 453-B, A Close, 14 Road, 2nd Avenue Gwarinpa, FCT Abuja, FEDERAL REPUBLIC OF NIGERIA",
    Field11: "Address",
    Field12: "Monday-Friday \r\n8:30 a.m. to 5:30 p.m",
    Field13: "OFFICE HOURS",
    Field14:
      "\nH.E. (Mr.) Alex V. Lamadrid Ambassador Extraordinary and Plenipotentiary",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/2455",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Greece in Abuja, Nigeria",
    Field:
      "Phone\n+234 9 46 12 775 or 776, +234 9 78 22 762, +234 9 41 39 433 or 434",
    Field1: "Phone",
    Field2: "+ 234 9 46 12 778, +234 9 41 39 435",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://grembnigeria.mfa.gr/",
    Field6: " http://grembnigeria.mfa.gr/ ",
    Field7: "Email",
    Field8: "gremb_abj@mfa.gr",
    Field9: "gremb_abj@mfa.gr",
    Field10: "Plot 6, Seguela Street, Wuse II Off Ibb Way P.O. Box 11525",
    Field11: "Address",
    Field12: "\n09:00 - 16:00",
    Field13: "OFFICE HOURS",
    Field14: "\nHead of Mission: H.E. Ambassador Haralambos Dafaranos",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/2524",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Italy in Abuja, Nigeria",
    Field: "+234 09 5244036",
    Field1: "Phone",
    Field2: "+234 09 5244034",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.ambabuja.esteri.it/",
    Field6: " http://www.ambabuja.esteri.it ",
    Field7: "Email",
    Field8: "ambasciata.abuja@esteri.it",
    Field9: "ambasciata.abuja@esteri.it",
    Field10:
      "21st Crescent Off Constitution Avenue Central Business District Abuja, Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/3215",
    caps: "SEND EDITS",
  },
  {
    Title: "Australian High Commission in Abuja, Nigeria",
    Field: "+234 9 461 2780",
    Field1: "Phone",
    Field2: "+234 9 461 2782",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.nigeria.embassy.gov.au/aaja/home.html",
    Field6: " http://www.nigeria.embassy.gov.au/aaja/home.html ",
    Field7: "Email",
    Field8: "ahc.abuja@dfat.gov.au",
    Field9: "ahc.abuja@dfat.gov.au",
    Field10:
      "5th Floor, Oakland Centre 48 Aguiyi Ironsi Street, Maitama PMB 5152, Wuse Post Office Abuja Nigeria",
    Field11: "Address",
    Field12:
      "Monday to Thursday\r\n08:00 - 16:30\r\n\r\nFriday\r\n08:00 - 13:00\r\n",
    Field13: "OFFICE HOURS",
    Field14: "\nMr Jon Richardson - High Commissioner",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/3709",
    caps: "SEND EDITS",
  },
  {
    Title: "Deputy High Commission of Canada in Lagos, Nigeria",
    Field: "(011 234 1) 271-5650",
    Field1: "Phone",
    Field2: "(011 234 1) 271-5651",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.nigeria.gc.ca/",
    Field6: " http://www.nigeria.gc.ca ",
    Field7: "Email",
    Field8: "lagos@international.gc.ca",
    Field9: "lagos@international.gc.ca",
    Field10: "\n4 Anifowoshe Street Victoria Island, Lagos, Nigeria",
    Field11: "Address",
    Field12:
      "\nMonday - Thursday: 8:00 a.m. - 4:30 p.m. Friday: 8:00 a.m. - 1:30 p.m.",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/3847",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Chad in Lagos, Nigeria",
    Field: "234 1 261 2590",
    Field1: "Phone",
    Field2: "234 1 261 8314",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "",
    Field9: "",
    Field10: "\n2 Goriola Street Victoria Island",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/3869",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of the State of Eritrea in Nigeria",
    Field: "+234-8139856889",
    Field1: "Phone",
    Field2: "+234-9-413-6085",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "eriemba_nigeria@yahoo.com",
    Field9: "eriemba_nigeria@yahoo.com",
    Field10: "Plot 1510 Yedseram street, off IBB way,   Maitama, Abuja",
    Field11: "Address",
    Field12: "\nMonday - Friday 07:30 - 15:30",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/4133",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Ethiopia in Nigeria",
    Field: "(+234) 09-4618641 or 42 or 43",
    Field1: "Phone",
    Field2: "(+234) 09-4618640",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "etembabuja@yahoo.com",
    Field9: "etembabuja@yahoo.com",
    Field10:
      "Plot No 332 Cadastral Zone AO Mission Road, Central District Garki, Abuja, Nigeria",
    Field11: "Address",
    Field12: "\nMonday to Friday 8:30 am to 4:00 pm",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/4159",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of the Czech Republic in Abuja, Nigeria",
    Field: "+234 703 757 10 96",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.mfa.cz/abuja",
    Field6: " http://www.mfa.cz/abuja ",
    Field7: "Email",
    Field8: "abuja@embassy.mzv.cz",
    Field9: "abuja@embassy.mzv.cz",
    Field10:
      "5, Gnassingbe Eyadema Street,  Asokoro, P.O.Box 4628  Abuja, Federal Republic of Nigeria",
    Field11: "Address",
    Field12: "\nMo - Fr, 08:00 - 16:00",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/4524",
    caps: "SEND EDITS",
  },
  {
    Title: "Royal Danish (Denmark) Consulate General in Lagos, Nigeria",
    Field: "+234 (1) 262 6430, ext. 8101",
    Field1: "Phone",
    Field2: "+234 (1) 262 6428",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "ngaconsuldk@maersk.com",
    Field9: "ngaconsuldk@maersk.com",
    Field10:
      "Maersk House 121 Louis Solomon Close P.O.Box 72554 Victoria Island, Lagos Nigeria",
    Field11: "Address",
    Field12: "\n10:00 am to 2:00 pm",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/4581",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of German in Nigeria, Lagos Office",
    Field: "+234 (1) 261 1011",
    Field1: "Phone",
    Field2: "+234 (1) 261 1173",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "gembassylagos@micro.com.ng",
    Field9: "gembassylagos@micro.com.ng",
    Field10: "15, Walter Carrington Crescent Victoria Island P.O. Box 728",
    Field11: "Address",
    Field12: ": 07:30 h - 15:00 h \r\nVisa Applicants: 07:00 h - 09:00 h",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/4795",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Finland in Abuja, Nigeria",
    Field: "+234 803 785 1150, (234-9) 314 7256, 341 6482",
    Field1: "Phone",
    Field2: "(234-9) 314 7252",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.finlandnigeria.org/",
    Field6: " http://www.finlandnigeria.org ",
    Field7: "Email",
    Field8: "sanomat.aba@formin.fi",
    Field9: "sanomat.aba@formin.fi",
    Field10: "\n9 Iro Dan Musa Street Asokoro",
    Field11: "Address",
    Field12: "\nMon-Thu 08.00-16.15, Fri 08.00-13.15",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/4846",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Argentina in Abuja, Nigeria",
    Field: "(234) 8093664820 / (234) 8093664821",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://enige.cancilleria.gov.ar/",
    Field6: " http://enige.cancilleria.gov.ar/ ",
    Field7: "Email",
    Field8: "enige@cancilleria.gob.ar",
    Field9: "enige@cancilleria.gob.ar",
    Field10:
      "30 Nelson Mandela Street, off Desmond Tutu, Asokoro, Abuja (CP :)",
    Field11: "Address",
    Field12: "\n9 a.m. to 3 p.m.",
    Field13: "OFFICE HOURS",
    Field14:
      "GUSTAVO ALEJANDRO DZUGALA. - Ambassador\r\n\r\nConsular Circumscription:\r\nFederal Republic of Nigeria, Benin, Republic of Burkina Faso, Republic of Cameroon, Central African Republic, Republic of Chad, Republic of Congo (Brazaville), Republic of Côte d'Ivoire, Republic of Gabon, Republic of Gambia, Republic of Ghana, Republic of Guinea, Republic of Guinea Bissau, Republic of Equatorial Guinea, Republic of Liberia, Republic of Mali, Republic of Niger, Republic of Sao Tome and Principe, Republic of Senegal, Republic of Sierra Leone, Republic of Togo.",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/5088",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Romania in Abuja, Nigeria",
    Field: "(00) (234) (9) 3142304 or 3142305",
    Field1: "Phone",
    Field2: "(00) (234) (9) 3142306",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "romnig@gmail.com",
    Field9: "romnig@gmail.com",
    Field10:
      "Plot No.498, Nelson Mandela Street Zone A4, Asokoro, Abuja, FCT or P.O.Box 10376 Garki",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/5253",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Sweden in Abuja, Nigeria",
    Field: "+234 9 291 5427",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "ambassaden.abuja@gov.se",
    Field9: "ambassaden.abuja@gov.se",
    Field10: "\n41 T. Y. Danjuma Street Asokoro District Abuja Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/5749",
    caps: "SEND EDITS",
  },
  {
    Title: "Australian Consulate in Lagos, Nigeria",
    Field: "+234 1 8179492, +234 803 300 7291",
    Field1: "Phone",
    Field2: "+234 1 8935409",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "alan.davies@jamescubittarchitects.com",
    Field9: "alan.davies@jamescubittarchitects.com",
    Field10:
      "8th Floor Union Marble House 1 Alfred Rewane Road (formerly Kingsway), Falomo Ikoyi Lagos Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/5902",
    caps: "SEND EDITS",
  },
  {
    Title: "High Commission of Malaysia in Abuja, Nigeria",
    Field: "+234-92908488",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.kln.gov.my/perwakilan/abuja",
    Field6: " http://www.kln.gov.my/perwakilan/abuja ",
    Field7: "Email",
    Field8: "mwabuja@kln.gov.my",
    Field9: "mwabuja@kln.gov.my",
    Field10:
      "No. 4A, Plot 2232 B Rio Negro Close, off Yedseram Street Maitama, Abuja",
    Field11: "Address",
    Field12:
      "Work day: Monday - Friday : 0830hrs -1630hrs\r\n\r\nConsular Section/Visa Application/Collection: 0900hrs-1230hrs (Procession period - 5 working days)\r\n\r\nHoliday: Saturday & Sunday",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/5948",
    caps: "SEND EDITS",
  },
  {
    Title: "Royal Netherlands Embassy in Abuja, Nigeria",
    Field: "+234-(0)9-4611200",
    Field1: "Phone",
    Field2: "+234-(0)9-4611240",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.mfa.nl/abj-en/",
    Field6: " http://www.mfa.nl/abj-en/ ",
    Field7: "Email",
    Field8: "abj@minbuza.nl",
    Field9: "abj@minbuza.nl",
    Field10:
      "21st Crescent, off Constitution Avenue, Central Business District",
    Field11: "Address",
    Field12: "\nMonday to Friday from 9:00 to 16:00",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/6240",
    caps: "SEND EDITS",
  },
  {
    Title: "United Kingdom (British) High Commission in Abuja, Nigeria",
    Field: "+234 (9) 4622200",
    Field1: "Phone",
    Field2: "+234(9) 4622263",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.gov.uk/government/world/nigeria",
    Field6: " http://www.gov.uk/government/world/nigeria ",
    Field7: "Email",
    Field8: "PPAInformation.abuja@fco.gov.uk",
    Field9: "PPAInformation.abuja@fco.gov.uk",
    Field10: "\n19 Torrens Close, Mississippi, Maitama Abuja, Nigeria",
    Field11: "Address",
    Field12: "\nMonday - Thursday: 8am-4pm. <br> Friday: 8am-1pm",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/6264",
    caps: "SEND EDITS",
  },
  {
    Title: "United Kingdom (British) Deputy High Commission in Lagos, Nigeria",
    Field: "+ 234 (1) 277 0780/0781/0782",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "consular.lagos@fco.gov.uk",
    Field9: "consular.lagos@fco.gov.uk",
    Field10: "11 Walter Carrington Crescent Victoria Island Lagos, Nigeria",
    Field11: "Address",
    Field12:
      "\nMonday to Thursday: 8.30 am to midday <br> Friday: 8.30 am to 11 am (GMT +1)",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/6268",
    caps: "SEND EDITS",
  },
  {
    Title:
      "The Trade Mission of the ROC Taiwan in Abuja, Federal Republic of Nigeria",
    Field: "(002-234-9) 4138321",
    Field1: "Phone",
    Field2: "(002-234-9) 4138326",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.roc-taiwan.org/NG",
    Field6: " http://www.roc-taiwan.org/NG ",
    Field7: "Email",
    Field8: "roctmtaiwan@yahoo.com",
    Field9: "roctmtaiwan@yahoo.com",
    Field10:
      "31, Katsina Ala Crescent Maitama, Abuja, Nigeria P.O. Box?P. M. B. 5111",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/6717",
    caps: "SEND EDITS",
  },
  {
    Title: "Royal Norwegian Embassy in Abuja, Nigeria",
    Field: "+234 (0) 9 314 91 27/28/29 or 30",
    Field1: "Phone",
    Field2: "+234 (0) 9 314 93 09",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.emb-norway.com.ng/Embassy/embassy/",
    Field6: " http://www.emb-norway.com.ng/Embassy/embassy/ ",
    Field7: "Email",
    Field8: "emb.abuja@mfa.no",
    Field9: "emb.abuja@mfa.no",
    Field10: "\n54, T.Y. Danjuma Street, Asokoro",
    Field11: "Address",
    Field12: "\nMonday to Friday from 09:00 to 16:00",
    Field13: "OFFICE HOURS",
    Field14: "\nH.E. Ambassador Kjell Lillerud",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/6817",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Algeria in Abuja, Nigeria",
    Field: "(+234) 9 314 28 40 / 1",
    Field1: "Phone",
    Field2: "(+234) 9 413 28 42",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "Informat@ambalglosanova.net.ng",
    Field9: "Informat@ambalglosanova.net.ng",
    Field10:
      "Plot 1398 Honorable Justice Mamman Nasir Street Asokoro District Abuja Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\nSmaïli Belkacem, Ambassador",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/7369",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Cuba in Abuja, Nigeria",
    Field: "461) 4821/22",
    Field1: "Phone",
    Field2: "(461) 4820",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.cubadiplomatica.cu/nigeria",
    Field6: " http://www.cubadiplomatica.cu/nigeria ",
    Field7: "Email",
    Field8: "embajada@ng.embacuba.cu",
    Field9: "embajada@ng.embacuba.cu",
    Field10: "Plot 339 Diplomatic Drive Central District Area Abuja Nigeria",
    Field11: "Address",
    Field12:
      "\nMonday through Thursday, 10:00 am. and 12:00 pm Closed on holidays in Cuba",
    Field13: "OFFICE HOURS",
    Field14: "\nAmbassador: Hugo Ramos Milanés",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/7743",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Thailand in Nigeria",
    Field: "(+234) 706 308 0403",
    Field1: "Phone",
    Field2: "00234 9413 5193",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.thaiembassynigeria.com/",
    Field6: " http://www.thaiembassynigeria.com/ ",
    Field7: "Email",
    Field8: "thaiabj@mfa.go.th",
    Field9: "thaiabj@mfa.go.th",
    Field10:
      "Royal Thai Embassy 24 Tennesse Cresent  Off Panama Street Maitama,  Abjua, Nigeria",
    Field11: "Address",
    Field12: "\nOffice Hours 8:30-16:30",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/7907",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Indonesia in Lagos, Nigeria",
    Field: "(234-1) 261-4601",
    Field1: "Phone",
    Field2: "(234-1) 261-3301",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.indonesianig.com/",
    Field6: " http://www.indonesianig.com ",
    Field7: "Email",
    Field8: "kbri_lagos@yahoo.co.id",
    Field9: "kbri_lagos@yahoo.co.id",
    Field10: "5 Anifowoshe Street Victoria Island, Abuja Lagos, Nigeria",
    Field11: "Address",
    Field12: "\nMonday to Thursday 10:00 am to 12:00 noon; 3:00 pm to 4:00 pm",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/8247",
    caps: "SEND EDITS",
  },
  {
    Title: "High Commission of the Republic of Kenya in Abuja, Nigeria",
    Field: "+ 234 9 4139 155",
    Field1: "Phone",
    Field2: "+ 234 9 4139 157",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "kenyahi@alpha.lindserve.com",
    Field9: "kenyahi@alpha.lindserve.com",
    Field10: "21 Yedseram Street Maitama, P.M.B. 5160 Wuse Head Office",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14:
      "\nOther countries of Accreditation: Republic of Cote DIvoire, Togo, Republic of Ghana, Liberia, Benin, Sierra Leone",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/8639",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Israel in Abuja, Nigeria",
    Field: "234 9 3143170; 234 9 6739552",
    Field1: "Phone",
    Field2: "234 9 3143177",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://abuja.mfa.gov.il/",
    Field6: " http://abuja.mfa.gov.il ",
    Field7: "Email",
    Field8: "consular-assist@abuja.mfa.gov.il",
    Field9: "consular-assist@abuja.mfa.gov.il",
    Field10:
      "Plot 12, Mary Slessor Street Off Udo Udoma Crescent Asokoro, Abuja P.O.Box 10924, Garki",
    Field11: "Address",
    Field12: "\nMonday - Friday : 10:00 - 13:00",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/8883",
    caps: "SEND EDITS",
  },
  {
    Title: "Maltese Honorary Consulate in Lagos, Nigeria",
    Field: "(+234) 806 260 1996; (+234) 802 302 3876",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "maltaconsul.lagos@gov.mt",
    Field9: "maltaconsul.lagos@gov.mt",
    Field10: "10, Atinuke Olabanji Street P.O. Box 2688 Ikeja Lagos Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/9727",
    caps: "SEND EDITS",
  },
  {
    Title: "Saudi Arabian Embassy in Nigeria",
    Field: "002347098221442, 0023497822675",
    Field1: "Phone",
    Field2: "00234134906",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://embassies.mofa.gov.sa/sites/Nigeria/en/Pages/default.aspx",
    Field6:
      " http://embassies.mofa.gov.sa/sites/Nigeria/en/Pages/default.aspx ",
    Field7: "Email",
    Field8: "Ngemb@mofa.gov.sa",
    Field9: "Ngemb@mofa.gov.sa",
    Field10:
      "The Royal Embassy Of Saudi Arabia No.6 Orange Street Thames , the Off Alvan Lkoku Way Ministers' Hill Maitama , Abuja",
    Field11: "Address",
    Field12: "\nFrom S 9:00 pm To 4:00 am",
    Field13: "OFFICE HOURS",
    Field14:
      "\nH.E. Mr. Fahad bin Abdullah Alsefyan - Ambassador of the Custodian of the Two Holy Mosques in the federal Republic of Nigeria",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/9955",
    caps: "SEND EDITS",
  },
  {
    Title: "Senegalese Embassy in Lagos, Nigeria",
    Field: "+234-1-611722",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "",
    Field9: "",
    Field10: "\n14, Kofo Abayomi Road PO Box 2197",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/10131",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Togo in Nigeria",
    Field: "(01) 261.7478",
    Field1: "Phone",
    Field2: "(01) 261.7448",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "",
    Field9: "",
    Field10: "Plot 976 Oju-Olobun Close Victoria Island Lagos, Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/11025",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Turkey in Abuja, Nigeria",
    Field: "00 234 8036488981",
    Field1: "Phone",
    Field2: "00 234-9 413 94 57",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://abuja.emb.mfa.gov.tr/",
    Field6: " http://abuja.emb.mfa.gov.tr ",
    Field7: "Email",
    Field8: "embassy.abuja@mfa.gov.tr",
    Field9: "embassy.abuja@mfa.gov.tr",
    Field10:
      "Plot: 333 Diplomatic Drive, Central Business District Abuja, Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/11111",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Tunisia in Nigeria",
    Field: "+234-1-2618150",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "",
    Field9: "",
    Field10: "\nPlot 79, Younis Basorun Street Victoria Island",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/11287",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Ukraine in Nigeria",
    Field: "(00234) 709821-21-58",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://nigeria.mfa.gov.ua/",
    Field6: " http://nigeria.mfa.gov.ua ",
    Field7: "Email",
    Field8: "emb_ng@ukr.net",
    Field9: "emb_ng@ukr.net",
    Field10: "\n15 Moundou Street Wuse II, Abuja",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/11625",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Ireland in Nigeria",
    Field: "+ 234 9 4620611",
    Field1: "Phone",
    Field2: "+ 234 9 4131805 + 234 9 4620613",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.embassyofireland.org.ng/",
    Field6: " http://www.embassyofireland.org.ng ",
    Field7: "Email",
    Field8: "abujaembassy@dfa.ie",
    Field9: "abujaembassy@dfa.ie",
    Field10: "\nNo 11 Negro Crescent Maitama District",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "Ambassador: His Excellency Patrick Fay  ",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/11715",
    caps: "SEND EDITS",
  },
  {
    Title: "High Commission of Canada in Abuja, Nigeria",
    Field: "(011 234 9) 413 99 10",
    Field1: "Phone",
    Field2: "(011 234 9) 413-9932",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.nigeria.gc.ca/",
    Field6: " http://www.nigeria.gc.ca ",
    Field7: "Email",
    Field8: "abuja@international.gc.ca",
    Field9: "abuja@international.gc.ca",
    Field10: "\n15 Bobo Street, Maitama Abuja, Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/12125",
    caps: "SEND EDITS",
  },
  {
    Title: "Jamaican High Commission, Abuja",
    Field: "234 9 780 6809 / 08036008758 / 08136063356",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "jamaicanembassy@yahoo.com",
    Field9: "jamaicanembassy@yahoo.com",
    Field10:
      "3rd Floor, NICON Plaza, 242 Muhammadu Buhari Way Central Area District, Abuja, N",
    Field11: "Address",
    Field12: "Monday - Thursday  8:30am to 4pm\r\nFriday  8:30am - 3pm",
    Field13: "OFFICE HOURS",
    Field14:
      "High Comissioner:    His Excellency Robert E. Miller\r\n\r\nCountries of Accreditation: Nigeria, Ghana, Cameroon, Sierra Leone, Senegal",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/12147",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Brazil in Abuja, Nigeria",
    Field: "(+234) 803 535 0118, (+234) 9 461 8688",
    Field1: "Phone",
    Field2: "(+234) 9-461.8687",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "brasemb.abuja@itamaraty.gov.br",
    Field9: "brasemb.abuja@itamaraty.gov.br",
    Field10: "324 Diplomatic Drive, Central Business District Abuja Nigeria",
    Field11: "Address",
    Field12: "\n08:00 - 17:00",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/12421",
    caps: "SEND EDITS",
  },
  {
    Title: "Consulate of Uruguay in Nigeria",
    Field: "(+234) 1 261 6430",
    Field1: "Phone",
    Field2: "+234-1-261 94 77",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "a.moudaber@gmail.com",
    Field9: "a.moudaber@gmail.com",
    Field10: "Plot 979, Saka Jojo Street, Victoria Island Lagos, Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/12511",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Russia in Lagos, Nigeria",
    Field: "(+234-1) 261-22-67, 261-50-22, 261-33-59",
    Field1: "Phone",
    Field2: "(+234-1) 461-99-94",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "RusEmLagos@vgccl.net",
    Field9: "RusEmLagos@vgccl.net",
    Field10: "\n5, Walter Carrington Crescent, Victoria Island",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/12549",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Venezuela in Nigeria",
    Field: "+2349-3140900",
    Field1: "Phone",
    Field2: "+2349-3140901",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "embavenez-nig@nova.net.ng",
    Field9: "embavenez-nig@nova.net.ng",
    Field10:
      "Plot 1631 Hon, Justice Sowewimo Street Asokoro District Abuja, Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/12893",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Tanzania in Nigeria",
    Field: "+234-1-613604",
    Field1: "Phone",
    Field2: "+234-1-610016 / +234-1-618908",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "",
    Field9: "",
    Field10: "\n8 Agoro Odiyan Street, Victoria Island",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/13023",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Serbia in Nigeria",
    Field: "+234-1-2690912 / +234-1-2694202",
    Field1: "Phone",
    Field2: "+234-1-2691889",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "embscgnig@nova.net.ng",
    Field9: "embscgnig@nova.net.ng",
    Field10: "\n7, Maitama Sule Street, S/W IKOYI PO Box 978",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/13229",
    caps: "SEND EDITS",
  },
  {
    Title: "Consulate-General of the Republic of Singapore - Nigeria (Lagos) ",
    Field: "+234-1-4619088",
    Field1: "Phone",
    Field2: "+234-1-4610828",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "hcg.sin.ng@gmail.com",
    Field9: "hcg.sin.ng@gmail.com",
    Field10:
      "3rd Floor, Lagoon View Plaza, Plot A4, Ozumba Mbadiwe Street, Victoria Island",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/13417",
    caps: "SEND EDITS",
  },
  {
    Title: "High Commission of India in Lagos, Nigeria",
    Field: "00-234-1-2627680, 2615909",
    Field1: "Phone",
    Field2: "00-234-1-2612660",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.hicomindlagos.com/",
    Field6: " http://www.hicomindlagos.com/ ",
    Field7: "Email",
    Field8: "hclag@hyperia.com",
    Field9: "hclag@hyperia.com",
    Field10: "\n8-A, Walter Carrington Crescent Victoria Island",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/13737",
    caps: "SEND EDITS",
  },
  {
    Title: "High Commission of India in Abuja, Nigeria (Branch Office)",
    Field: "00-234-9-5236099",
    Field1: "Phone",
    Field2: "00-234-9-5236088",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "hicomindabj@linkserve.com",
    Field9: "hicomindabj@linkserve.com",
    Field10:
      "Plot No. 684 (A&B), Agdez Crescent Off Aminu Kano Crescent Wuse-II",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/13739",
    caps: "SEND EDITS",
  },
  {
    Title: "Royal Danish Consulate General in Nigeria",
    Field: "+234 (1) 262 6430, ext. 8101",
    Field1: "Phone",
    Field2: "+234 (1) 262 6428",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "ngaconsuldk@maersk.com",
    Field9: "ngaconsuldk@maersk.com",
    Field10:
      "Maersk House 121 Louis Solomon Close P.O.Box 72554 Victoria Island, Lagos",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14:
      "The Faroe Islands and Greenland are part of the Kingdom of Denmark. As a main principle, the Danish Constitution stipulates that the foreign and security interests for all parts of the Kingdom of Denmark are the responsibility of the Danish government.\r\n",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/14371",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Spain in Nigeria",
    Field: "(+234) (9) 461 32 58 / 71 / 73",
    Field1: "Phone",
    Field2: "(+234) (9) 461 32 59",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "emb.abuja@maec.es",
    Field9: "emb.abuja@maec.es",
    Field10:
      "8 Bobo Close off Gana Street Maitama District P.M.B. 5120 Wuse Post Office Abuja Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "Mr Alvaro Castillo Aguilar - Ambassador\r\n",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/14467",
    caps: "SEND EDITS",
  },
  {
    Title: "Consulate of Spain in Nigeria",
    Field: "(+234) (1) 461 76 18 (+234) (1) 280 54 88",
    Field1: "Phone",
    Field2: "(+234) (1) 461 73 97",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "cog.lagos@maec.es",
    Field9: "cog.lagos@maec.es",
    Field10:
      "21 Cs Kofo Abayomi Road P.O. Box: 74759 Victoria Island Lagos Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\nCarolina de Manueles elvarez - Consul General",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/14473",
    caps: "SEND EDITS",
  },
  {
    Title: "Consulate of Zimbabwe in Abuja, Nigeria",
    Field: "(234-9) 4611322 / 5239924",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "zimabuja@infoweb.abs.net",
    Field9: "zimabuja@infoweb.abs.net",
    Field10: "Plot 2908, Cadstral Zone A6 Maitama District Abuja, Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/14599",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Honduras in Nigeria",
    Field: "(00 - 234 - 9) 314-1180, 314-1181,314-1183",
    Field1: "Phone",
    Field2: "(00 - 234 - 9) 314-1177",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.mfa.gov.hu/emb/abuja",
    Field6: " http://www.mfa.gov.hu/emb/abuja ",
    Field7: "Email",
    Field8: "mission.abv@kum.hu",
    Field9: "mission.abv@kum.hu",
    Field10: "\nNo. 61, Jose Marti Crescent, Asokoro",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/14879",
    caps: "SEND EDITS",
  },
  {
    Title: "Ugandan High Commission in Abuja, Nigeria ",
    Field: "(+234) 9-413 8069",
    Field1: "Phone",
    Field2: "(+234) 9-413 8070",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "ugandabuja@surichtech.com",
    Field9: "ugandabuja@surichtech.com",
    Field10:
      "Plot 28 Ontario Crescent, Off Mississippi Street Ministers Hill Maitama Postal Address: P.M.B. 223 Abuja, Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/15105",
    caps: "SEND EDITS",
  },
  {
    Title: "High Commission of Namibia in Abuja, Nigeria",
    Field: "(+234) 9-314-2740/1/2/4",
    Field1: "Phone",
    Field2: "(+234) 9-314-2743",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "namibiahcabuja@premiernetng.net",
    Field9: "namibiahcabuja@premiernetng.net",
    Field10:
      "Namibian High Commission Plot 1738 T.Y. Danjuma Street Asokoro P.M.B 5097, Wuse",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\nHigh Commissioner: Mr. Philemon Kambala",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/15933",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Mali in Nigeria",
    Field: "(+234) 803 172 2702: (+234) 806 036 1597",
    Field1: "Phone",
    Field2: "Fax ",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "ambassademaliabuja@yahoo.fr",
    Field9: "ambassademaliabuja@yahoo.fr",
    Field10: "\nPlot 3257, Ibrahim Babangida Way Maitama Abuja Nigeria",
    Field11: "Address",
    Field12: "\n9am - 4pm",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/16429",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Slovakia in Nigeria",
    Field: "(+234-9) 3143731/+234-9-3143732",
    Field1: "Phone",
    Field2: "(+234-9) 3143730",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.mzv.sk/Abuja",
    Field6: " http://www.mzv.sk/Abuja ",
    Field7: "Email",
    Field8: "zusrnigeria@yahoo.com",
    Field9: "zusrnigeria@yahoo.com",
    Field10: "\nNo. 14 Lord Lugard Street P.M.B. 582",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/16617",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Pakistan in Abuja, Nigeria",
    Field: "+234 9 3141650",
    Field1: "Phone",
    Field2: "+234 9 314165",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "pahicabuja@yahoo.com",
    Field9: "pahicabuja@yahoo.com",
    Field10: "Plot No.4 (Old Number 1805) Samora Machel Street, Asokoro",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/18305",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Bulgaria in Abuja, Nigeria",
    Field: "+234 8033078578",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.mfa.bg/embassies/nigeria/",
    Field6: " http://www.mfa.bg/embassies/nigeria/ ",
    Field7: "Email",
    Field8: "Embassy.Abuja@mfa.bg",
    Field9: "Embassy.Abuja@mfa.bg",
    Field10: "10, Euphrates St. off Aminu Kano Crescent Maitama Abuja Nigeria",
    Field11: "Address",
    Field12: "\n09:00 - 12:30",
    Field13: "OFFICE HOURS",
    Field14: "\nVesselin Delchev - Ambassador",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/18948",
    caps: "SEND EDITS",
  },
  {
    Title: "Consulate General of France in Lagos, Nigeria",
    Field: "[234] (1) 46 28 484",
    Field1: "Phone",
    Field2: "[234] (1) 46 28 480",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.consulfrance-lagos.org/",
    Field6: " http://www.consulfrance-lagos.org/ ",
    Field7: "Email",
    Field8: "consulfrance.lagos@diplomatie.gouv.fr",
    Field9: "consulfrance.lagos@diplomatie.gouv.fr",
    Field10: "\nIkoyi Island - 1 Oyinkan Abayomi Drive",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/19243",
    caps: "SEND EDITS",
  },
  {
    Title: "High Commission of Cameroon in Abuja, Nigeria",
    Field: "(+234) (9) 461 1355",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "info@cameroonhighcomabuja.com",
    Field9: "info@cameroonhighcomabuja.com",
    Field10: "Plot 469/470 Lobito Crescent Wuse II - FCT Abuja Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\nMr Salaheddine Abbas Ibrahima, High Commissioner",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/19339",
    caps: "SEND EDITS",
  },
  {
    Title: "Zambian High Commission in Lagos, Nigeria",
    Field: "(+234-1) 2690426 /7",
    Field1: "Phone",
    Field2: "(+234-1) 2690426",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "zambiahc@yahoo.com",
    Field9: "zambiahc@yahoo.com",
    Field10:
      "18, Alhaji Babatunde Jose Road Victoria Island P.O Box 6119, Lagos Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/19657",
    caps: "SEND EDITS",
  },
  {
    Title: "General Consulate of Italy in Lagos, Nigeria",
    Field: "0023414627419",
    Field1: "Phone",
    Field2: "00234-1- 4627418",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.conslagos.esteri.it/",
    Field6: " http://www.conslagos.esteri.it ",
    Field7: "Email",
    Field8: "visti.lagos@esteri.it",
    Field9: "visti.lagos@esteri.it",
    Field10: "\n12, Walter Carrington Crescent, Victoria Island - Lagos",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/19818",
    caps: "SEND EDITS",
  },
  {
    Title: "Consulate General of Belize in Abuja, Nigeria",
    Field: "(+234) 813 060 9533",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "info@theconsulateofbelize.org",
    Field9: "info@theconsulateofbelize.org",
    Field10:
      "24 Nkwere Street off Ahmadu Bello Way Area 11, Garki Abuja Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\nDr. Ifeanyichukwu Ifedi - Honorary Consul General",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/19878",
    caps: "SEND EDITS",
  },
  {
    Title: "Honorary Consul of Barbados in Lagos, Nigeria",
    Field: "(+234) 1 470-0252",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "tunde.barbados@gmail.com",
    Field9: "tunde.barbados@gmail.com",
    Field10:
      "Penthouse, Yinka Folawiyo Plaza 38 Warehouse Road Apapa Lagos Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\nMr Babatunde Folawiyo - Consul",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/19970",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of the Sahrawi Arab Democratic Republic in Nigeria",
    Field: "(+234-9) 413 6980",
    Field1: "Phone",
    Field2: "(+234-9) 413 6980",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "embsahrawi@hotmail.com",
    Field9: "embsahrawi@hotmail.com",
    Field10: "\nAbuja, Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/20000",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of  Hungary in Asokoro, Nigeria",
    Field: "706-478-6188",
    Field1: "Phone",
    Field2: "9-3141177",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.mfa.gov.hu/emb/abuja",
    Field6: " http://www.mfa.gov.hu/emb/abuja ",
    Field7: "Email",
    Field8: "mission.abv@kum.hu",
    Field9: "mission.abv@kum.hu",
    Field10:
      "No. 61, Jose Marti Crescent, Plot 1685, Asokoro,  Abuja, Nigeria   P. O. BOX 5299",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/20214",
    caps: "SEND EDITS",
  },
  {
    Title: "Honorary Consulate of Belgium in Lagos, Nigeria",
    Field: "+234 803 535 29 86",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "consubel.lagos@gmail.com",
    Field9: "consubel.lagos@gmail.com",
    Field10:
      "Dredging International Service Nigeria Alfred Rewane Road 35A Ikoyi Lagos Nigeria",
    Field11: "Address",
    Field12: "\nonly by appointment",
    Field13: "OFFICE HOURS",
    Field14: "\nDirk Raeymaekers - Honorary Consul",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/20997",
    caps: "SEND EDITS",
  },
  {
    Title: "Consulate of Canada in Port Harcourt, Nigeria",
    Field:
      "Phone\n234 (84) 890-903 <br> Emergency line for Canadians 234 8063 9970 54",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "phconsul2004@yahoo.com",
    Field9: "phconsul2004@yahoo.com",
    Field10:
      "15, Ahoada Road, Rumuibekwe Housing Estate Port Harcourt, Nigeria",
    Field11: "Address",
    Field12:
      "\nMonday - Thursday: 8:00 a.m. - 4:30 p.m. <br> Friday: 8:00 a.m. - 1:30 p.m.",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/21302",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Austria in Abuja, Nigeria",
    Field: "(+234) 706 41 83 226",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.bmeia.gv.at/botschaft/abuja.html",
    Field6: " http://www.bmeia.gv.at/botschaft/abuja.html ",
    Field7: "Email",
    Field8: "abuja-ob@bmeia.gv.at",
    Field9: "abuja-ob@bmeia.gv.at",
    Field10: "\nPlot 9, Usuma Street Maitama Abuja Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/21327",
    caps: "SEND EDITS",
  },
  {
    Title: "Honorary Consulate of Austria in Kaduna, Nigeria",
    Field: "(+234) 705 7000 700, (+234) 808 7000 700",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "austriaconsul@live.com",
    Field9: "austriaconsul@live.com",
    Field10: "\n3A, Kinkino Road, G.R.A. Kaduna Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\nMr Hermann Hufnagl - Consul",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/21330",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Switzerland in Abuja, Nigeria",
    Field: "(+234) 9-461 0540 / 1",
    Field1: "Phone",
    Field2: "(+234) 9-461 0548",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.eda.admin.ch/abuja",
    Field6: " http://www.eda.admin.ch/abuja ",
    Field7: "Email",
    Field8: "abu.vertretung@eda.admin.ch",
    Field9: "abu.vertretung@eda.admin.ch",
    Field10: "No 157, Adetokumbo Ademola Crescent Wuse II Abuja Nigeria",
    Field11: "Address",
    Field12: "Monday-Friday \r\n09:00-11:00",
    Field13: "OFFICE HOURS",
    Field14: "\nAmbassador: Dr Andreas Baum",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/21642",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of the Kingdom of Morocco in Abuja, Nigeria",
    Field: "+234 1 2611682",
    Field1: "Phone",
    Field2: "+234 1 2612269",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "",
    Field9: "",
    Field10: "\nPlot 1306 Udo Udoma Crescent, Asokoro, Abuja",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/22366",
    caps: "SEND EDITS",
  },
  {
    Title: "Chinese Embassy in Abuja, Nigeria  ",
    Field: "00234-9-4618661<br>00234-9-4618662<br>00234-9-4618664",
    Field1: "Phone",
    Field2: "00234-9-4618660",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://ng.chineseembassy.org/eng",
    Field6: " http://ng.chineseembassy.org/eng ",
    Field7: "Email",
    Field8: "chinaemb_ng@mfa.gov.cn",
    Field9: "chinaemb_ng@mfa.gov.cn",
    Field10: "\nPlot 302-303 Ao. Central Area Abuja",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/22534",
    caps: "SEND EDITS",
  },
  {
    Title: "Chinese Consulate General in Lagos, Nigeria",
    Field: "2612586",
    Field1: "Phone",
    Field2: "2715583",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://lagos.china-consulate.org/",
    Field6: " http://lagos.china-consulate.org ",
    Field7: "Email",
    Field8: "Chinaconsul_lg_ng@mfa.gov.cn",
    Field9: "Chinaconsul_lg_ng@mfa.gov.cn",
    Field10: "\nPlot 161A, Idejo Street Victoria Island, Lagos, Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/22535",
    caps: "SEND EDITS",
  },
  {
    Title: "High Commission of Ghana in Nigeria",
    Field: "(+234-1) 614527",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "",
    Field9: "",
    Field10:
      "No 23b Oba Akinjobi street, Ikeja GRA, close to Police command, Ikeja",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/23029",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Equatorial Guinea in Lagos, Nigeria ",
    Field: "(234 1) 269 12 11",
    Field1: "Phone",
    Field2: "(234 1) 261 60 62",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "",
    Field9: "",
    Field10: "\nP.O. Box 4126",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/23180",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Gabon in Lagos, Nigeria",
    Field: "(234-1) 68 45 66",
    Field1: "Phone",
    Field2: "(234-1) 269 0692",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "",
    Field9: "",
    Field10: "\n8 Norman William Street BP 5989",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/23213",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Egypt in Abuja, Nigeria",
    Field: "00234(0)7034158802, 00234(0)7064184050",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5:
      "http://www.mfa.gov.eg/english/embassies/Egyptian_Embassy_Nigeria/Pages/default.aspx",
    Field6:
      " http://www.mfa.gov.eg/english/embassies/Egyptian_Embassy_Nigeria/Pages/default.aspx ",
    Field7: "Email",
    Field8: "embassy.abuja@mfa.gov.eg",
    Field9: "embassy.abuja@mfa.gov.eg",
    Field10: "\nPlot 340, Diplomatic Drive, Central Area - Abuja",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/23909",
    caps: "SEND EDITS",
  },
  {
    Title: "Consulate General of Egypt in Lagos, Nigeria",
    Field: "+2341 – 4604029",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5:
      "http://www.mfa.gov.eg/english/embassies/Egyptian_Consulate_Lagos/Pages/default.aspx",
    Field6:
      " http://www.mfa.gov.eg/english/embassies/Egyptian_Consulate_Lagos/Pages/default.aspx ",
    Field7: "Email",
    Field8: "egypconsulateinlagos@yahoo.com",
    Field9: "egypconsulateinlagos@yahoo.com",
    Field10: "\nNO: 5 OBA ELUGUSHI - IKOYI - LAGOS – NIGERIA",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/23911",
    caps: "SEND EDITS",
  },
  {
    Title: "Honorary Consulate of Hungary in Nigeria",
    Field: "234-204; Mobile: (00-234)-803-311-7578",
    Field1: "Phone",
    Field2: "240-456",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "hunconskad@yahoo.co.uk",
    Field9: "hunconskad@yahoo.co.uk",
    Field10: "\nKaduna, 4 Abba Habib Road P. O. Box 2958",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/24415",
    caps: "SEND EDITS",
  },
  {
    Title: "Honorary Consulate of Hungary in Nigeria",
    Field: "461-9618",
    Field1: "Phone",
    Field2: "461-9617",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "billyaigbe@yahoo.com",
    Field9: "billyaigbe@yahoo.com",
    Field10:
      "Azosik Brothers International Limited  Shop F-5  V.G.C. Shopping Complex  Victoria Garden City, Epe Expressway, Ikota, Lagos",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/24416",
    caps: "SEND EDITS",
  },
  {
    Title: "Palestine Embassy in Nigeria",
    Field: "+234 9 4611420; +2348035873641",
    Field1: "Phone",
    Field2: "+234 9 4611437",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "palestine_emb_abuja@yahoo.com",
    Field9: "palestine_emb_abuja@yahoo.com",
    Field10: "Plot 346, Diplomatic Drive Behind U.N House, Central Area",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/24922",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Poland in Nigeria",
    Field: "+234.8076631021",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.abuja.polemb.net/",
    Field6: " http://www.abuja.polemb.net/ ",
    Field7: "Email",
    Field8: "abuja.amb.sekretariat@msz.gov.pl",
    Field9: "abuja.amb.sekretariat@msz.gov.pl",
    Field10:
      "10, Ona Crescent Off Lake Chad, Off IBB Way, Plot 775, Maitama 900271",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/25128",
    caps: "SEND EDITS",
  },
  {
    Title: "Honorary Commissioner of the Republic of Cyprus in Nigeria",
    Field: "(002341) 2806706",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "gfashina@agleventis.com",
    Field9: "gfashina@agleventis.com",
    Field10:
      "A. G. Leventis Building  Iddo House Oyingbo, Ebut-Metta  Lagos, Nigeria",
    Field11: "Address",
    Field12: "\n08:00  17:00",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/25518",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Palestine in Abuja, Nigeria",
    Field: "2349-4135311/0528-9",
    Field1: "Phone",
    Field2: "2349-4135308",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "ngemb@mofa-gov.ps",
    Field9: "ngemb@mofa-gov.ps",
    Field10: "\nNo. 34 Labito Crescent Wuse 2 Abuja Nigeria - -",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/25624",
    caps: "SEND EDITS",
  },
  {
    Title: "Sierra Leonean High Commission in Abuja, Nigeria",
    Field: "(+234) 987-254-13",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://www.slhcnigeria.org/",
    Field6: " http://www.slhcnigeria.org ",
    Field7: "Email",
    Field8: "info@slhcnigeria.org",
    Field9: "info@slhcnigeria.org",
    Field10:
      "Plot 308 Mission Road, Diplomatic Zone, FCT Abuja Federal Republic of Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/25824",
    caps: "SEND EDITS",
  },
  {
    Title: "South African High Commission in Abuja",
    Field: "+ 234 9 462 4200",
    Field1: "Phone",
    Field2: "+ 234 9 413 3776",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "irozani@gmail.com",
    Field9: "irozani@gmail.com",
    Field10: "\n71 Usuma Street off Gana Street Maitama Abuja - - -",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/25887",
    caps: "SEND EDITS",
  },
  {
    Title: "Belarussian Embassy in Abuja, Nigeria",
    Field: "(+234) 809 623 3210",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "http://nigeria.mfa.gov.by/",
    Field6: " http://nigeria.mfa.gov.by/ ",
    Field7: "Email",
    Field8: "nigeria@mfa.gov.by",
    Field9: "nigeria@mfa.gov.by",
    Field10: "1866, Deng Xioping Street Plot 2148  Asokoro Abuja  Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\nMr Vyacheslav Beskosty - Ambassador",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/26426",
    caps: "SEND EDITS",
  },
  {
    Title: "Syrian Embassy in Abuja, Nigeria ",
    Field: "(+234) 9 413 8507 (+234) 9 413 8334 / 5",
    Field1: "Phone",
    Field2: "(+234) 9 413 8337",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "",
    Field9: "",
    Field10:
      "Plot 2420 Maitama Area 6 Off Amazon Street   P.O. Box 393 Garki  Abuja Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/26591",
    caps: "SEND EDITS",
  },
  {
    Title: "High Commission of Botswana in Abuja, Nigeria",
    Field: "(+234) 97 822181/ 782",
    Field1: "Phone",
    Field2: "(+234) 7034 103 830",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "botnig@mail.org",
    Field9: "botnig@mail.org",
    Field10:
      "PLOT 1241, OGUTA LAKE STREET (OFF RIVER BENUE STREET) MAITAMA, EXTENSION ABUJA NIGERIA",
    Field11: "Address",
    Field12: "Monday to Friday \r\n08:30 - 13:00 and 14:00 - 16:30",
    Field13: "OFFICE HOURS",
    Field14: "\nMr Louis M. Fisher - HIGH COMMISSIONER",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/26662",
    caps: "SEND EDITS",
  },
  {
    Title: "Consulate General in Brazil in Lagos, Nigeria",
    Field:
      "Phone\n(+234) 805 4002 145, 803 6590 556, (+234) (1) 462-8958 to 60",
    Field1: "Phone",
    Field2: "(+234) (1) 461-1474, (+234) (1) 261-3394",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "brazilianconsulatelagos@gmail.com",
    Field9: "brazilianconsulatelagos@gmail.com",
    Field10: "Plot 257, Kofo Abayomi Street  Victoria Island  Lagos Nigeria",
    Field11: "Address",
    Field12: "\n09:30 - 12:30",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/26867",
    caps: "SEND EDITS",
  },
  {
    Title: "Embassy of Burkina Faso in Lagos, Nigeria",
    Field: "+234 9 413 04 91",
    Field1: "Phone",
    Field2: "-",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "Ebfn@nova.net.ng",
    Field9: "Ebfn@nova.net.ng",
    Field10: "\n4, Freetown Street Wuse II Lagos Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\nSEM YAMEOGO Dramane - Ambassador",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/27233",
    caps: "SEND EDITS",
  },
  {
    Title: "Angolan Embassy in Abuja, Nigeria",
    Field: "(+234) (9) 413 51 21",
    Field1: "Phone",
    Field2: "(+234) (9) 413 41 36",
    Field3: "Fax",
    Field4: "Website",
    Field5: "",
    Field6: "",
    Field7: "Email",
    Field8: "gabembnig@linkserve.org",
    Field9: "gabembnig@linkserve.org",
    Field10: "\nPMB 5145 Wuse - zone 3 Abuja Nigeria",
    Field11: "Address",
    Field12: "\n-",
    Field13: "OFFICE HOURS",
    Field14: "\n-",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/27377",
    caps: "SEND EDITS",
  },
  {
    Title: "United States Consulate General in Lagos, Nigeria",
    Field: "(234)-1-460-3400",
    Field1: "Phone",
    Field2: "(234)-1-261-9856",
    Field3: "Fax",
    Field4: "Website",
    Field5: "https://ng.usembassy.gov/embassy-consulate/lagos/",
    Field6: " https://ng.usembassy.gov/embassy-consulate/lagos/ ",
    Field7: "Email",
    Field8: "",
    Field9: "",
    Field10: "2 Walter Carrington Crescent Victoria Island, Lagos Nigeria",
    Field11: "Address",
    Field12:
      "Monday – Thursday\r\n7:00 a.m. to 4:00 p.m.\r\n\r\nFriday\r\n7:00 a.m. to 1:00 p.m.",
    Field13: "OFFICE HOURS",
    Field14: "\nConsul General: F. John Bray",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/27551",
    caps: "SEND EDITS",
  },
  {
    Title: "United States Consulate General in Lagos, Nigeria",
    Field: "(234)-1-460-3400",
    Field1: "Phone",
    Field2: "(234)-1-261-9856",
    Field3: "Fax",
    Field4: "Website",
    Field5: "https://ng.usembassy.gov/embassy-consulate/lagos/",
    Field6: " https://ng.usembassy.gov/embassy-consulate/lagos/ ",
    Field7: "Email",
    Field8: "LagosACS@state.gov",
    Field9: "LagosACS@state.gov",
    Field10: "2 Walter Carrington Crescent Victoria Island, Lagos Nigeria",
    Field11: "Address",
    Field12:
      "Monday – Thursday\r\n7:00 a.m. to 4:00 p.m.\r\n\r\nFriday\r\n7:00 a.m. to 1:00 p.m.",
    Field13: "OFFICE HOURS",
    Field14: "\nConsul General: F. John Bray",
    Field15: "Details",
    caps_URL: "https://embassy.goabroad.com/embassy/edit/27552",
    caps: "SEND EDITS",
  },
];
